image: registry.cn-shanghai.aliyuncs.com/space1/complile-python-3.8.12:v1.1

stages:
  - test
  - release

job lint:
  tags:
  - sp
  stage: test
  before_script:
    - source /data/www/venv/bin/activate
    - pip3 install mypy
  script:
  - mypy app

job pack_wheel:
  stage: release
  before_script:
    - yum install libffi-devel -y
    - source /data/www/venv/bin/activate
    - pip install twine
    - echo "[distutils]" >> ~/.pypirc
    - echo "index-servers=pypi" >> ~/.pypirc
    - echo "[pypi]" >> ~/.pypirc
    - echo "repository = http://mirrors.idiaoyan.cn/repository/pypi-release/" >> ~/.pypirc
    - echo "username = pypi" >> ~/.pypirc
    - echo "password = aTR6b1i9bgKmqojpC" >> ~/.pypirc
  script:
    - python setup.py bdist_wheel --universal
    - twine upload dist/* --verbose
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success
  tags:
    - sp