"""empty message

Revision ID: 58d46109fba0
Revises: 48be71cf0742
Create Date: 2021-11-01 10:28:30.570466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d46109fba0'
down_revision = '48be71cf0742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fe_owner_id', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_box_fe_owner_id'), ['fe_owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_box_fe_owner_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('fe_owner_id')

    # ### end Alembic commands ###
