"""empty message

Revision ID: 62b23e96ffd8
Revises: 
Create Date: 2021-10-25 19:23:52.476413

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = '62b23e96ffd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box',
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.Enum('off', 'on', 'error', name='boxstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('port_prefix', sa.Integer(), nullable=True),
    sa.Column('numprocs', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('box', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_box_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_box_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_box_numprocs'), ['numprocs'], unique=False)
        batch_op.create_index(batch_op.f('ix_box_port_prefix'), ['port_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_box_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_box_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_box_user_id'), ['user_id'], unique=False)

    op.create_table('project',
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uat_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('port_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_command', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url_paths', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_project_port_prefix'), ['port_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_run_command'), ['run_command'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_uat_name'), ['uat_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_url_paths'), ['url_paths'], unique=False)

    op.create_table('user',
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))

    op.drop_table('user')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_url_paths'))
        batch_op.drop_index(batch_op.f('ix_project_uat_name'))
        batch_op.drop_index(batch_op.f('ix_project_run_command'))
        batch_op.drop_index(batch_op.f('ix_project_port_prefix'))
        batch_op.drop_index(batch_op.f('ix_project_name'))
        batch_op.drop_index(batch_op.f('ix_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_domain'))
        batch_op.drop_index(batch_op.f('ix_project_created_at'))

    op.drop_table('project')
    with op.batch_alter_table('box', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_box_user_id'))
        batch_op.drop_index(batch_op.f('ix_box_start_time'))
        batch_op.drop_index(batch_op.f('ix_box_project_id'))
        batch_op.drop_index(batch_op.f('ix_box_port_prefix'))
        batch_op.drop_index(batch_op.f('ix_box_numprocs'))
        batch_op.drop_index(batch_op.f('ix_box_id'))
        batch_op.drop_index(batch_op.f('ix_box_created_at'))

    op.drop_table('box')
    # ### end Alembic commands ###
